const CONSTANT_LITERALS = {
	PROPERTY_TYPE: {
		RESIDENTIAL: 'RESIDENTIAL',
		COMMERCIAL: 'COMMERCIAL',
		INDUSTRIAL: 'INDUSTRIAL',
		OPEN_PLOT: 'OPEN-PLOT',
		AGRICULTURAL: 'AGRICULTURAL',
	},
	CLIENT_TYPE: {
		SALE: 'SALE',
		RENT: 'RENT',
	},
	SALE_PARTY: {
		BUYER: 'BUYER',
		SELLER: 'SELLER',
	},
	RENT_PARTY: {
		RENTER: 'RENTER',
		HOMEOWNER: 'HOMEOWNER',
	},
	LEAD: {
		WALK_IN: 'WALK-IN',
		ONLINE: 'ONLINE',
		REFERENCE: 'REFERENCE',
	},
	LEAD_ONLINE_NAME: {
		UNKNOWN: 'UNKNOWN',
		JUST_DIAL: 'JUST-DIAL',
		SQUARE_YARDS: 'SQUARE-YARDS',
	},
	DEAL_STATUS: {
		ONGOING: 'ONGOING',
		CLOSED: 'CLOSED',
		DROPPED: 'DROPPED',
	},
	VALUES: {
		MIN_BUDGET: 0,
		MAX_RENT_BUDGET: 300000,
		MAX_SALE_BUDGET: 100000000,
		MIN_AREA: 0,
		MAX_AREA: 5000,
	},
};

module.exports = CONSTANT_LITERALS;
